// Regenerate the Wazo ACL catalog shipped at `@wazo/types/acl`.
//
// Fetches every Wazo OpenAPI spec at build time, reads the `**Required ACL:** `<acl>`` annotations,
// groups them by service, and writes the committed runtime module src/acl/catalog.generated.ts.
//
// Run standalone with:  node --experimental-strip-types ./src/acl/generate.ts
// (also runs as part of `npm run generate`).

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';

import { buildCatalog, extractAcls } from './acl-extract.ts';
import { SPECS } from '../specs.ts';

const OUTPUT = path.resolve(process.cwd(), 'src', 'acl', 'catalog.generated.ts');
const VERSION_URL = 'https://mirror.wazo.community/version/stable';

const fetchText = async (url: string): Promise<string> => {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`${url} → HTTP ${res.status}`);
  }
  return res.text();
};

// `{ canonicalServiceKey: string[] }` of ACLs for every spec in a layer. Keyed by the spec's
// canonical stem (from SPECS), never the URL — so dev/edge overrides can't collapse services.
const collectLayer = async (layer: 'stack' | 'portal'): Promise<Record<string, string[]>> => {
  const out: Record<string, string[]> = {};
  await Promise.all(
    SPECS.filter(spec => spec.layer === layer).map(async spec => {
      const acls = extractAcls(await fetchText(spec.url));
      if (acls.length) {
        // Merge rather than overwrite in case two specs share a canonical key within a layer.
        out[spec.key] = Array.from(new Set([...(out[spec.key] ?? []), ...acls]));
      }
    }),
  );
  return out;
};

const resolveApiVersion = async (): Promise<string> => {
  try {
    return (await fetchText(VERSION_URL)).trim();
  } catch {
    // Fall back to the package version (calendar-versioned to track the API).
    const pkg = JSON.parse(fs.readFileSync(path.resolve(process.cwd(), 'package.json'), 'utf8'));
    return pkg.version as string;
  }
};

const render = (catalog: unknown): string => {
  const json = JSON.stringify(catalog, null, 2);
  return `// AUTO-GENERATED by src/acl/generate.ts — do not edit by hand.
// Refresh with: npm run generate  (or: node --experimental-strip-types ./src/acl/generate.ts)
// Source: Wazo OpenAPI specs (\`Required ACL\` annotations).

import type { AclCatalog } from './types';

export const WAZO_ACL_CATALOG: AclCatalog = ${json};

export const ALL_ACLS: readonly string[] = WAZO_ACL_CATALOG.allAcls;
`;
};

const main = async (): Promise<void> => {
  // Mirror build.ts: a .env means specs are fetched from a custom/unstable environment, so the
  // catalog is not the stable one that should be committed/published.
  if (fs.existsSync(path.resolve(process.cwd(), '.env'))) {
    console.warn('⚠️  .env detected: generating the ACL catalog from custom/unstable specs — do not commit this output.');
  }

  const [apiVersion, stack, portal] = await Promise.all([
    resolveApiVersion(),
    collectLayer('stack'),
    collectLayer('portal'),
  ]);

  const catalog = buildCatalog(stack, portal, apiVersion);

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, render(catalog), 'utf8');

  console.log(`✅ ACL catalog: version ${apiVersion}, ${catalog.services.length} services, ${catalog.allAcls.length} ACLs`);
  console.log(`   wrote ${path.relative(process.cwd(), OUTPUT)}`);
};

main().catch(error => {
  console.error(`❌ Failed to generate ACL catalog: ${error instanceof Error ? error.message : error}`);
  process.exit(1);
});
