// Build the Wazo ACL catalog shipped at `@wazo/types/acl`.
//
// Reads the `**Required ACL:** `<acl>`` annotations from each Wazo OpenAPI spec, groups them by
// service, and writes the committed runtime module src/acl/catalog.generated.ts.
//
// The helpers below are also called by the single-fetch orchestrator (src/build.ts) with specs it
// already downloaded, so the combined `npm run generate` fetches each spec only once.
//
// Run standalone with:  node --experimental-strip-types ./src/acl/generate.ts
// (this path fetches the specs itself).

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as process from 'node:process';
import { pathToFileURL } from 'node:url';

import { buildCatalog, extractAcls } from './acl-extract.ts';
import { fetchAllSpecs, fetchText, type FetchedSpec } from '../specs.ts';

const OUTPUT = path.resolve(process.cwd(), 'src', 'acl', 'catalog.generated.ts');
const VERSION_URL = 'https://mirror.wazo.community/version/stable';

// `{ canonicalServiceKey: string[] }` of ACLs per layer, built from already-fetched spec texts.
// Keyed by the spec's canonical stem (from SPECS), never the URL — so dev/edge overrides can't
// collapse services.
export const collectAclLayers = (
  specs: FetchedSpec[],
): { stack: Record<string, string[]>; portal: Record<string, string[]> } => {
  const layers = {
    stack: {} as Record<string, string[]>,
    portal: {} as Record<string, string[]>,
  };
  for (const { spec, text } of specs) {
    const acls = extractAcls(text);
    if (!acls.length) {
      continue;
    }
    const map = layers[spec.layer];
    // Merge rather than overwrite in case two specs share a canonical key within a layer.
    map[spec.key] = Array.from(new Set([...(map[spec.key] ?? []), ...acls]));
  }
  return layers;
};

export const resolveApiVersion = async (): Promise<string> => {
  try {
    return (await fetchText(VERSION_URL)).trim();
  } catch {
    // Fall back to the package version (calendar-versioned to track the API).
    const pkg = JSON.parse(fs.readFileSync(path.resolve(process.cwd(), 'package.json'), 'utf8'));
    return pkg.version as string;
  }
};

const render = (catalog: unknown): string => {
  const json = JSON.stringify(catalog, null, 2);
  return `// AUTO-GENERATED by src/acl/generate.ts — do not edit by hand.
// Refresh with: npm run generate  (or: node --experimental-strip-types ./src/acl/generate.ts)
// Source: Wazo OpenAPI specs (\`Required ACL\` annotations).

import type { AclCatalog } from './types';

export const WAZO_ACL_CATALOG: AclCatalog = ${json};

export const ALL_ACLS: readonly string[] = WAZO_ACL_CATALOG.allAcls;
`;
};

// Build the catalog from grouped ACL layers and write the committed runtime module.
export const writeCatalog = (
  stack: Record<string, string[]>,
  portal: Record<string, string[]>,
  apiVersion: string,
): void => {
  const catalog = buildCatalog(stack, portal, apiVersion);

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, render(catalog), 'utf8');

  console.log(`✅ ACL catalog: version ${apiVersion}, ${catalog.services.length} services, ${catalog.allAcls.length} ACLs`);
  console.log(`   wrote ${path.relative(process.cwd(), OUTPUT)}`);
};

// Standalone entry: fetch specs, then build + write. `build.ts` calls the helpers above directly
// with specs it already fetched, so the combined `npm run generate` downloads each spec only once.
const main = async (): Promise<void> => {
  // Mirror build.ts: a .env means specs are fetched from a custom/unstable environment, so the
  // catalog is not the stable one that should be committed/published.
  if (fs.existsSync(path.resolve(process.cwd(), '.env'))) {
    console.warn('⚠️  .env detected: generating the ACL catalog from custom/unstable specs — do not commit this output.');
  }

  const [apiVersion, specs] = await Promise.all([resolveApiVersion(), fetchAllSpecs()]);
  const { stack, portal } = collectAclLayers(specs);
  writeCatalog(stack, portal, apiVersion);
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch(error => {
    console.error(`❌ Failed to generate ACL catalog: ${error instanceof Error ? error.message : error}`);
    process.exit(1);
  });
}
